spring.datasource.url=jdbc:mysql://vittae-db-instance.cbi2jrxark3t.us-east-1.rds.amazonaws.com:3306/vittae?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=vittae_user
spring.datasource.password=vittae1231
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
server.port=8080
api.base.url=http://44.197.126.129:8080/vittae