INSERT IGNORE INTO especialidade (nome, descricao) VALUES 
('Administração em Saúde', 'Gestão, planejamento e organização de serviços de saúde públicos ou privados'), 
('Alergia e Imunologia Pediátrica', 'Diagnóstico e tratamento de doenças alérgicas e imunológicas em crianças'), 
('Angiorradiologia e Cirurgia Endovascular', 'Procedimentos diagnósticos e terapêuticos invasivos do sistema vascular'), 
('Atendimento ao Queimado', 'Tratamento clínico e cirúrgico de pacientes com queimaduras graves'), 
('Avaliador de Doenças Neuromusculares', 'Avaliação diagnóstica especializada de patologias dos nervos e músculos'), 
('Cardiologia Pediátrica', 'Diagnóstico e tratamento de cardiopatias congênitas em crianças'), 
('Cardiologia Intervencionista', 'Procedimentos por cateterismo para tratamento de doenças cardíacas'), 
('Cirurgia Bariátrica', 'Tratamento cirúrgico da obesidade mórbida e suas comorbidades'), 
('Cirurgia Crânio-Maxilo-Facial', 'Tratamento de deformidades e tumores dos ossos da face e crânio'), 
('Cirurgia do Trauma', 'Atendimento cirúrgico de emergência a vítimas de causas externas'), 
('Cirurgia Dermatológica', 'Procedimentos cirúrgicos diagnósticos e estéticos realizados na pele'), 
('Cirurgia Espinhal', 'Tratamento cirúrgico de patologias e fraturas da coluna vertebral'), 
('Cirurgia Oncoplástica da Mama', 'Reconstrução mamária aliada ao tratamento cirúrgico do câncer'), 
('Citopatologia', 'Estudo e diagnóstico de doenças por meio de análises de células'), 
('Densitometria Óssea', 'Exame de diagnóstico por imagem para avaliação da osteoporose'), 
('Dor', 'Tratamento multidisciplinar e controle de quadros de dores crônicas'), 
('Ecocardiografia', 'Avaliação anatômica do coração por meio de ultrassonografia cardíaca'), 
('Ecografia Vascular com Doppler', 'Mapeamento do fluxo sanguíneo nas artérias e veias por ultrassom'), 
('Eletrofisiologia Clínica Invasiva', 'Estudo e tratamento invasivo das arritmias cardíacas'), 
('Endocrinologia Pediátrica', 'Tratamento de distúrbios hormonais e diabetes em crianças'), 
('Endoscopia Digestiva', 'Diagnóstico de doenças do esôfago, estômago e cólon por tubo flexível'), 
('Endoscopia Ginecológica', 'Laparoscopia e histeroscopia para diagnóstico e cirurgia uterina'), 
('Endoscopia Respiratória', 'Visualização e biópsias da árvore brônquica por broncoscopia'), 
('Ergometria', 'Realização de testes de esforço para avaliação cardiorrespiratória'), 
('Estimulação Cardíaca Artificial', 'Implante e acompanhamento de marcapassos e desfibriladores'), 
('Foniatria', 'Diagnóstico e tratamento de distúrbios da comunicação oral e escrita'), 
('Gastroenterologia Pediátrica', 'Tratamento de doenças do sistema digestório e fígado em crianças'), 
('Hansenologia', 'Estudo, tratamento especializado e controle da hanseníase'), 
('Hematologia e Hemoterapia Pediátrica', 'Doenças do sangue e terapias transfusionais focadas na infância'), 
('Hemodinâmica e Cardiologia Intervencionista', 'Diagnóstico de cardiopatias por meio de cateterismo cardíaco'), 
('Hepatologia', 'Diagnóstico e manejo clínico de doenças do fígado e vias biliares'), 
('Infectologia Pediátrica', 'Tratamento de infecções bacterianas e virais na infância'), 
('Mamografia', 'Exame radiológico para rastreamento de câncer de mama'), 
('Medicina Aeroespacial', 'Prevenção de problemas de saúde relacionados a voos espaciais'), 
('Medicina do Adolescente (Hebiatria)', 'Atendimento integrado focado no desenvolvimento de adolescentes'), 
('Medicina do Sono', 'Diagnóstico de distúrbios como apneia obstrutiva e insônia'), 
('Medicina Fetal', 'Acompanhamento do feto, exames genéticos e cirurgias intrauterinas'), 
('Medicina Intensiva Pediátrica', 'Suporte avançado de vida e monitoramento de crianças em UTI'), 
('Medicina Intensiva Neonatal', 'Suporte de vida avançado para recém-nascidos críticos em UTIN'), 
('Medicina Paliativa', 'Cuidados focados no alívio do suffering de pacientes terminais'), 
('Medicina Tropical', 'Abordagem de doenças infecciosas prevalentes em regiões tropicais'), 
('Nefrologia Pediátrica', 'Diagnóstico e tratamento de doenças do sistema renal em crianças'), 
('Neonatologia', 'Assistência médica especializada ao recém-nascido até o 28º dia'), 
('Neurofisiologia Clínica', 'Análise do sistema nervoso por exames como eletroencefalograma'), 
('Neurologia Pediátrica', 'Diagnóstico e tratamento de distúrbios neurológicos em crianças'), 
('Nutrição Parenteral e Enteral', 'Manejo de terapias nutricionais injetáveis ou por sondas'), 
('Nutrologia Pediátrica', 'Abordagem médica de distúrbios nutricionais e obesidade na infância'), 
('Oftalmologia Pediátrica e Estrabismo', 'Correção de desvios oculares e tratamentos visuais na infância'), 
('Oncologia Pediátrica', 'Tratamento quimioterápico e clínico de tumores em crianças'), 
('Pneumologia Pediátrica', 'Tratamento de asma e patologias respiratórias crônicas na infância'), 
('Psicogeriatria', 'Diagnóstico de transtornos mentais e demências na população idosa'), 
('Psiquiatria da Infância e da Adolescência', 'Abordagem de transtornos mentais e desenvolvimento em jovens'), 
('Psiquiatria Forense', 'Avaliação pericial psiquiátrica aplicada a processos jurídicos'), 
('Radiologia Intervencionista e Angiorradiologia', 'Procedimentos terapêuticos mínimos guiados por imagem'), 
('Reprodução Assistida', 'Tratamentos de infertilidade e fertilização in vitro'), 
('Reumatologia Pediátrica', 'Diagnóstico de doenças autoimunes e inflamatórias na infância'), 
('Sexologia', 'Abordagem médica de disfunções e saúde sexual'), 
('Transplante de Medula Óssea', 'Gerenciamento de transplantes de células-tronco'), 
('Ultrassonografia em Ginecologia e Obstetrícia', 'Diagnóstico por ultrassom do aparelho reprodutor e gestação'),
('Gastroenterologia', 'Diagnóstico e tratamento clínico de doenças do aparelho digestivo'),
('Pediatria', 'Assistência médica especializada no desenvolvimento e doenças de crianças'),
('Clínico Geral', 'Atendimento médico preventivo, integral e direcionamento a especialidades'),
('Cardiologia', 'Diagnóstico, tratamento e prevenção de doenças do sistema cardiovascular');
