INSERT IGNORE INTO especialidade (nome, descricao) VALUES
('Clínico Geral', 'Atendimento médico preventivo, integral e direcionamento a especialidades'),
('Pediatria', 'Assistência médica especializada no desenvolvimento e doenças de crianças'),
('Ginecologia e Obstetrícia', 'Saúde do aparelho reprodutor feminino, gravidez e parto'),
('Cardiologia', 'Diagnóstico, tratamento e prevenção de doenças do sistema cardiovascular'),
('Dermatologia', 'Diagnóstico e tratamento de doenças da pele, cabelo e unhas'),
('Ortopedia e Traumatologia', 'Tratamento de lesões e doenças dos ossos, músculos e articulações'),
('Oftalmologia', 'Diagnóstico e tratamento de doenças e distúrbios da visão'),
('Otorrinolaringologia', 'Tratamento de doenças do ouvido, nariz e garganta'),
('Psiquiatria', 'Diagnóstico e tratamento de transtornos mentais e comportamentais'),
('Neurologia', 'Diagnóstico e tratamento de doenças do sistema nervoso'),
('Endocrinologia e Metabologia', 'Tratamento de distúrbios hormonais, diabetes e tireoide'),
('Urologia', 'Tratamento de doenças do trato urinário e sistema reprodutor masculino'),
('Gastroenterologia', 'Diagnóstico e tratamento clínico de doenças do aparelho digestivo'),
('Pneumologia', 'Diagnóstico e tratamento de doenças do sistema respiratório'),
('Reumatologia', 'Tratamento de doenças autoimunes, articulares e do tecido conjuntivo'),
('Nefrologia', 'Diagnóstico e tratamento de doenças renais'),
('Hematologia e Hemoterapia', 'Diagnóstico e tratamento de doenças do sangue'),
('Oncologia', 'Diagnóstico e tratamento de tumores e câncer'),
('Infectologia', 'Diagnóstico e tratamento de doenças infecciosas e parasitárias'),
('Geriatria', 'Atenção integral à saúde da pessoa idosa'),
('Nutrologia', 'Diagnóstico e tratamento de distúrbios nutricionais e obesidade'),
('Alergia e Imunologia', 'Diagnóstico e tratamento de alergias e doenças do sistema imunológico'),
('Anestesiologia', 'Avaliação pré-operatória e administração de anestesia em procedimentos'),
('Cirurgia Geral', 'Procedimentos cirúrgicos de diversas regiões e órgãos do corpo'),
('Cirurgia Plástica', 'Procedimentos reconstrutivos e estéticos do corpo'),
('Cirurgia Vascular', 'Tratamento clínico e cirúrgico de doenças das veias e artérias'),
('Mastologia', 'Diagnóstico e tratamento de doenças da mama'),
('Medicina do Trabalho', 'Avaliação da saúde do trabalhador e prevenção de doenças ocupacionais'),
('Radiologia e Diagnóstico por Imagem', 'Exames de imagem para diagnóstico médico'),
('Medicina da Família e Comunidade', 'Atendimento contínuo e integral ao paciente e sua família');